Repository kahluaband/Homepage_client_ver2.0, pull requests merged in 2024-12, with the labels that each got.

#119 Feat: 마이페이지 내 회원 탈퇴 및 예약 취소 기능
  components/mypage/List.tsx
  components/ui/ButtonModal.tsx
Labels: ✨ Feature

#120 Feat: CancelPopup ButtonModal 컴포넌트 사용하여 구현
  components/announcement/posting/CancelPopup.tsx
  components/announcement/posting/TopButtons.tsx
Labels: ✨ Feature

#116 Feat: 모달창 추가, 예약상태 추가
  app/(kahlua)/reservation/page.tsx
  components/reservation/Banner.tsx
  components/reservation/CalendarUI.css
  components/reservation/CalendarUI.tsx
  components/reservation/ReservationFailureModal.tsx
  components/reservation/ReservationForm.tsx
  components/reservation/ReservationSuccessModal.tsx
  components/reservation/TimeTable.tsx
  components/ui/Modal.tsx
  public/image/reservation/tabler_x.svg
Labels: 🔨 Refactor, ✨ Feature, 🔮Design

#122 Feat: DeletePopup ButtonModal 컴포넌트 사용하여 구현
  app/(kahlua)/announcement/post/page.tsx
  components/notice/Comment.tsx
  components/notice/DeleteCommentPopup.tsx
  components/notice/DeletePostPopup.tsx
  components/notice/Post.tsx
Labels: ✨ Feature

#121 Feat: admin page - performance, recruiting info page
  app/(kahlua)/admin/performanceInfo/page.tsx
  app/(kahlua)/admin/performanceInfo/performanceData.ts
  app/(kahlua)/admin/recruitingInfo/page.tsx
  app/(kahlua)/login/page.tsx
  components/admin/CancelModal.tsx
  components/admin/EditModal.tsx
  components/templates/admin/Info.tsx
  components/ui/Modal.tsx
  components/ui/admin/ImageBox.tsx
  components/ui/admin/IntBox.tsx
  components/ui/admin/TicketInfo.tsx
  components/ui/admin/type.ts
  components/util/isChanged.ts
Labels: 🔨 Refactor, ✨ Feature
