Repository kahluaband/Homepage_client_ver2.0, pull requests merged in 2024-08, with the labels that each got.

#37 Feat: 제작자 페이지 UI 구현 및 반응형 완성
  app/contributors/page.tsx
  components/Footer.tsx
  components/Header.tsx
  components/contributors/ContributorCard.tsx
  components/contributors/ContributorCardList.tsx
  components/contributors/ContributorList.tsx
  components/contributors/Title.tsx
  public/image/contributors/GH.avif
  public/image/contributors/GR.avif
  public/image/contributors/GY.avif
  public/image/contributors/JE.avif
  public/image/contributors/JY.avif
  public/image/contributors/SW.avif
  public/image/contributors/SY.avif
  public/image/contributors/blurCard.svg
  public/image/contributors/blurCard2.svg
  public/image/contributors/blurCard3.svg
  public/image/contributors/email.svg
  public/image/contributors/github.svg
  public/image/contributors/school.svg
  public/image/tabler_menu-2-white.svg
Labels: ✨ Feature, 🔮Design

#40 Remove: yarn.lock 제거
  yarn.lock
Labels: ✒️ Fix

#39 #Feat: recruit page API 연결
  app/recruit/(application)/apply/page.tsx
  components/main/PerformanceList.tsx
  components/performance/SongList.ts
  components/templates/apply/ApplicantInfo.tsx
  components/templates/apply/CLInfo.tsx
  components/templates/apply/OtherInfo.tsx
  components/ui/MultipleOptionbox.tsx
Labels: 🐞 BugFix, 📬 API

#42 Design: padding top 제거
  app/about/page.tsx
Labels: 🎨 Html&css, 🔮Design

#44 Fix: Ticket 수정사항 반영
  app/ticket/(check)/search/page.tsx
  app/ticket/(reserve)/complete/page.tsx
  app/ticket/(reserve)/freshman_ticket/page.tsx
  app/ticket/(reserve)/general_ticket/page.tsx
  app/ticket/page.tsx
  components/data/Information.tsx
  components/popups/ticket/LastCheckModal.tsx
  components/popups/ticket/LocaltionModal.tsx
  components/popups/ticket/ReservedErrorModal.tsx
  components/templates/ticket/FinalStep.tsx
  components/templates/ticket/FreshmanInfo.tsx
  components/templates/ticket/GeneralInfo.tsx
  components/templates/ticket/InfoTemplate.tsx
  components/templates/ticket/MemberSelection.tsx
  components/templates/ticket/TicketOption.tsx
  components/ui/DropDownBox.tsx
  components/ui/Ticket.tsx
  components/ui/TicketDetails.tsx
  components/ui/input.tsx
  components/util/utils.tsx
  public/image/ticket/addplus.svg
  public/image/ticket/subtract.svg
  tailwind.config.ts
Labels: ✨ Feature, ✒️ Fix

#47 Fix: Input 파일 명 변경
  app/ticket/(reserve)/general_ticket/page.tsx
  components/templates/apply/ApplicantInfo.tsx
  components/templates/apply/OtherInfo.tsx
  components/templates/ticket/FreshmanInfo.tsx
  components/templates/ticket/InfoTemplate.tsx
  components/ui/InputBox.tsx
Labels: ✒️ Fix

#48 Fix: Build 오류 및 API response 변경
  app/ticket/(check)/cancel/page.tsx
  app/ticket/(check)/reservation/page.tsx
  app/ticket/(reserve)/complete/page.tsx
  app/ticket/(reserve)/freshman_ticket/page.tsx
  app/ticket/(reserve)/general_ticket/page.tsx
  components/data/Information.tsx
Labels: 🌏 Deploy, 🐞 BugFix

#51 Fix: 티켓페이지 수정사항
  app/ticket/(reserve)/general_ticket/page.tsx
  app/ticket/page.tsx
  components/popups/ticket/LastCheckModal.tsx
  components/popups/ticket/ReservedErrorModal.tsx
Labels: 🌏 Deploy, 🐞 BugFix

#41 Feat: 어드민 페이지 통신 구현
  .github/workflows/deploy.yml
  api/auth/axios.ts
  app/(admin)/admin/applicant/page.tsx
  app/(admin)/admin/layout.tsx
  app/(admin)/admin/ticketing/page.tsx
  app/(admin)/kahlua-admin/layout.tsx
  app/(admin)/kahlua-admin/page.tsx
  app/(admin)/login/layout.tsx
  app/(admin)/login/page.tsx
  app/layout.tsx
  atoms/index.ts
  build.sh
  components/Footer.tsx
  components/Header.tsx
  components/admin/AdminHeader.tsx
  components/admin/LoginBox.tsx
  components/admin/applicant/ApplicantCard.tsx
  components/admin/ticketing/TicketLists.tsx
  components/performance/MainContainer.tsx
  components/performance/Playlists.tsx
  components/performance/YearSelector.tsx
  package-lock.json
  package.json
  public/image/admin/image.svg
  public/image/admin/tabler_book-2.svg
  public/image/admin/tabler_chevron-down.svg
  public/image/admin/tabler_device-mobile.svg
  public/image/admin/tabler_map-pin.svg
  public/image/admin/tabler_x.svg
  public/image/admin/ticketing.svg
Labels: ✨ Feature, 🔮Design, 📬 API

#55 Feat: open graph 설정
  app/favicon.ico
  app/manifest.ts
  app/opengraph-image.alt.txt
  app/opengraph-image.jpg
  app/recruit/(application)/notice/page.tsx
  app/recruit/page.tsx
  components/data/RecruitingInfo.ts
  components/data/SongList.ts
  components/main/PerformanceCard.tsx
  components/main/PerformanceList.tsx
Labels: ✨ Feature

#54 Fix: 배포 이슈 해결
  app/ticket/page.tsx
  components/popups/ticket/LastCheckModal.tsx
  components/popups/ticket/ReservedErrorModal.tsx
Labels: 🌏 Deploy, 🐞 BugFix

#57 Design: recruit page image 변경
  app/recruit/page.tsx
  components/main/Recruit.tsx
  public/image/recruit/bass.svg
  public/image/recruit/drum.svg
  public/image/recruit/guitar.svg
  public/image/recruit/syn.svg
Labels: 🔮Design

#58 Feat: og title, description
  app/layout.tsx
  app/recruit/page.tsx
  components/contributors/ContributorCard.tsx
  components/contributors/Title.tsx
  components/main/About.tsx
  components/main/Performance.tsx
  components/main/TicketInfo.tsx
  components/main/TicketIntro.tsx
  components/recruit/SessionCard.tsx
Labels: ✨ Feature

#65 Fix: performance 페이지 렌더링 오류 해결 및 성능 측정 도구 추가
  app/page.tsx
  components/main/PerformanceCard.tsx
  components/performance/Playlists.tsx
  components/performance/YearSelector.tsx
  package-lock.json
  package.json
Labels: 🌏 Deploy, 🐞 BugFix, 🔮Design

#66 Design: 기수 flex로 조절
  components/contributors/ContributorCard.tsx
Labels: 🔮Design, ✒️ Fix

#71 Fix: QA사항 반영
  app/ticket/(check)/reservation/page.tsx
  app/ticket/(reserve)/freshman_ticket/page.tsx
  app/ticket/(reserve)/general_ticket/page.tsx
  app/ticket/page.tsx
  components/data/Information.tsx
  components/popups/ticket/LocaltionModal.tsx
  components/templates/ticket/FinalStep.tsx
  components/templates/ticket/GeneralInfo.tsx
  components/templates/ticket/InfoTemplate.tsx
  components/templates/ticket/MustRead.tsx
  components/templates/ticket/TicketOption.tsx
  components/templates/ticket/TicketStatus.tsx
  components/ui/DropDownBox.tsx
Labels: ✒️ Fix

#72 Fix: 예매 페이지 인원 선택 오류 해결
  app/ticket/(reserve)/general_ticket/page.tsx
  components/templates/ticket/GeneralInfo.tsx
  components/templates/ticket/MemberSelection.tsx
Labels: ✒️ Fix

#75 Feat: Google Analytics 적용
  app/layout.tsx
  app/recruit/page.tsx
  components/Header.tsx
  components/contributors/ContributorCard.tsx
  components/contributors/Title.tsx
  components/main/About.tsx
  components/main/Performance.tsx
  components/main/PerformanceCard.tsx
  components/main/Recruit.tsx
  components/main/TicketInfo.tsx
  components/main/TicketIntro.tsx
  components/performance/MainContainer.tsx
  components/performance/Playlists.tsx
  components/recruit/SessionCard.tsx
  lib/GoogleAnalytics.tsx
Labels: 🌏 Deploy, 🥰 Accessibility

#81 Feat: dayjs 사용
  components/data/Information.tsx
  components/data/RecruitingInfo.ts
  package-lock.json
  package.json
Labels: 🌏 Deploy, 🐞 BugFix

#82 Feat: 포스터 이미지 적용
  app/ticket/page.tsx
  components/main/TicketIntro.tsx
  public/image/ticket/Poster.avif
  public/image/ticket/Poster.svg
Labels: 🔮Design

#86 Feat: main, recruit, image 수정사항
  app/manifest.ts
  app/recruit/page.tsx
  components/about/Concert.tsx
  components/data/Information.tsx
  components/main/About.tsx
  components/recruit/SessionCard.tsx
  public/image/about/guitar.svg
  public/image/about/music.svg
  public/image/main/mainMusic.svg
  public/image/main/music.svg
  public/image/recruit/bass.svg
  public/image/recruit/drum.svg
  public/image/recruit/guitar.svg
  public/image/recruit/syn.svg
  public/image/recruit/vocal.svg
Labels: ✨ Feature, 🔮Design

#78 배포 환경 수정사항 반영
  app/(admin)/admin/applicant/page.tsx
  app/(admin)/admin/ticketing/page.tsx
  app/(admin)/login/page.tsx
  app/layout.tsx
  app/page.tsx
  app/recruit/(application)/apply/page.tsx
  app/recruit/FAQ.tsx
  app/recruit/page.tsx
  app/ticket/(check)/cancel/page.tsx
  app/ticket/(check)/reservation/page.tsx
  app/ticket/(check)/search/page.tsx
  app/ticket/(reserve)/complete/page.tsx
  app/ticket/(reserve)/freshman_ticket/page.tsx
  app/ticket/(reserve)/general_ticket/page.tsx
  app/ticket/page.tsx
  components/Footer.tsx
  components/Header.tsx
  components/about/Card.tsx
  components/admin/AdminHeader.tsx
  components/admin/applicant/ApplicantCard.tsx
  components/admin/ticketing/TicketLists.tsx
  components/contributors/ContributorCard.tsx
  components/contributors/Title.tsx
  components/loading.tsx
  components/main/About.tsx
  components/main/Performance.tsx
  components/main/Recruit.tsx
  components/main/Ticket.tsx
  components/main/TicketInfo.tsx
  components/main/TicketIntro.tsx
  components/performance/Playlists.tsx
  components/templates/apply/ApplicantInfo.tsx
  components/templates/apply/CLInfo.tsx
  components/templates/apply/OtherInfo.tsx
  components/templates/ticket/InfoTemplate.tsx
  components/templates/ticket/MemberSelection.tsx
  components/templates/ticket/PartySelection.tsx
  components/util/delay.ts
  lib/GoogleAnalytics.tsx
  package-lock.json
  package.json
  public/readme_main.png
Labels: 🌏 Deploy, 🔨 Refactor

#90 Fix: 신입생 티켓 정보 삭제
  app/ticket/page.tsx
Labels: ✒️ Fix

#97 Fix: patch 로직 수정
  components/admin/ticketing/TicketLists.tsx
Labels: 🔨 Refactor, 📬 API

#99 Feat: 엑셀파일 다운로드 추가
  app/(admin)/admin/applicant/page.tsx
  app/(admin)/admin/ticketing/page.tsx
  app/recruit/(application)/notice/page.tsx
  app/recruit/page.tsx
  components/data/RecruitingInfo.ts
Labels: ✨ Feature
