Repository kahluaband/Homepage_client_ver2.0, pull requests merged in 2024-11, with the labels that each got.

#106 Feat: 공지사항 글쓰기 페이지 UI 구현 및 반응형
  app/announcement/posting/page.tsx
  app/globals.css
  components/announcement/posting/CancelPopup.tsx
  components/announcement/posting/CommunityRule.tsx
  components/announcement/posting/ContentInput.tsx
  components/announcement/posting/ImageUpload.tsx
  components/announcement/posting/TitleInput.tsx
  components/announcement/posting/TopButtons.tsx
Labels: ✨ Feature, 🔮Design

#108 Feat: 헤더 수정 구현
  app/(admin)/admin/ticketing/page.tsx
  app/mypage/page.tsx
  app/recruit/page.tsx
  components/Header.tsx
  components/admin/AdminHeader.tsx
  components/admin/ticketing/TicketLists.tsx
  components/contributors/Title.tsx
Labels: 🔨 Refactor, 🔮Design, ✒️ Fix

#110 Feat: login page UI 제작
  app/globals.css
  app/kahlua/admin/page.tsx
  app/kahluaLogin/info/page.tsx
  app/kahluaLogin/page.tsx
  components/kahluaLogin/LoginSelectBox.tsx
  components/kahluaLogin/loginModal.tsx
  components/kahluaLogin/nameInput.tsx
  components/ui/ButtonModal.tsx
  components/ui/Modal.tsx
  package-lock.json
  public/image/login/google.svg
  public/image/login/kakao.svg
  tailwind.config.ts
Labels: ✨ Feature, 🔮Design

#111 Feat: 게시글 페이지 UI 및 기능 구현
  app/layout.tsx
  app/notice/page.tsx
  components/notice/Comment.tsx
  components/notice/CommentInput.tsx
  components/notice/CommentList.tsx
  components/notice/DeleteCommentPopup.tsx
  components/notice/DeletePostPopup.tsx
  components/notice/LikeButton.tsx
  components/notice/Post.tsx
  components/notice/post/ContentSection.tsx
  components/notice/post/InfoSection.tsx
  components/notice/post/TitleSection.tsx
  components/util/noticeUtils.ts
  package-lock.json
  package.json
  public/image/notice/EmptyHeart.svg
  public/image/notice/FullHeart.svg
  public/image/notice/Left.svg
  public/image/notice/chat.svg
  public/image/notice/defaultProfile.svg
  public/image/notice/send.svg
Labels: ✨ Feature, 🔮Design

#112 Feat : Reservation page 퍼블리싱
  app/layout.tsx
  app/reservation/page.tsx
  components/reservation/Banner.tsx
  components/reservation/CalendarUI.css
  components/reservation/CalendarUI.tsx
  components/reservation/ReservationForm.tsx
  components/reservation/ReservationNotice.tsx
  components/reservation/RoomNotice.tsx
  components/reservation/TimeTable.tsx
  package-lock.json
  package.json
Labels: 🔨 Refactor, ✨ Feature

#115 Feat: admin page 레이아웃 구현
  app/(kahlua)/admin/page.tsx
  app/(kahlua)/admin/performanceInfo/page.tsx
  app/(kahlua)/admin/performanceInfo/performanceData.ts
  app/(kahlua)/admin/recruitingInfo/page.tsx
  app/(kahlua)/admin/recruitingInfo/recruitingData.ts
  app/(kahlua)/login/info/page.tsx
  app/(kahlua)/login/page.tsx
  app/PrevAdmin/admin/layout.tsx
  app/PrevAdmin/login/page.tsx
  app/layout.tsx
  components/admin/CancelModal.tsx
  components/admin/EditModal.tsx
  components/admin/adminPageButton.tsx
  components/data/RecruitingInfo.ts
  components/login/LoginSelectBox.tsx
  components/login/loginModal.tsx
  components/login/nameInput.tsx
  components/templates/admin/Info.tsx
  components/ui/Banner.tsx
  components/ui/ButtonModal.tsx
  components/ui/DropDownBox.tsx
  components/ui/Modal.tsx
  components/ui/admin/Button.tsx
  components/ui/admin/Date.tsx
  components/ui/admin/DateTime.tsx
  components/ui/admin/ImageBox.tsx
  components/ui/admin/IntBox.tsx
  components/ui/admin/TextBox.tsx
  components/ui/admin/type.ts
  components/util/isChanged.ts
  package-lock.json
  package.json
Labels: ✨ Feature

#114 Feat: 마이페이지 기능 + 반응형 구현
  app/(kahlua)/mypage/page.tsx
  components/mypage/List.tsx
  components/mypage/UserProfile.tsx
  public/image/mypage/grayChat.svg
  public/image/mypage/grayHeart.svg
  public/image/mypage/profile.png
Labels: ✨ Feature, 🔮Design

#117 Feat: 공지사항 리스트 페이지 UI 구현 및 반응형
  app/(kahlua)/announcement/page.tsx
  components/announcement/list/AnnouncementBanner.tsx
  components/announcement/list/AnnouncementList.tsx
  components/announcement/list/CommunityList.tsx
  components/announcement/list/List.tsx
  components/announcement/list/Pagination.tsx
  components/announcement/list/Toggle.tsx
  components/announcement/list/dto.ts
  components/announcement/list/dummy.ts
  components/util/formatDate.ts
  public/image/announcement/blackPen.svg
  public/image/announcement/blackSearch.svg
  public/image/grayChat.svg
  public/image/grayHeart.svg
Labels: ✨ Feature, 🔮Design

#118 Feat: 글 수정버튼 페이지 및 내용 연결
  app/(kahlua)/announcement/post/page.tsx
  app/(kahlua)/announcement/posting/page.tsx
  components/announcement/posting/ImageUpload.tsx
  components/announcement/posting/TopButtons.tsx
  components/notice/CommentInput.tsx
  components/notice/Post.tsx
  components/notice/post/ContentSection.tsx
  components/notice/post/TitleSection.tsx
Labels: ✨ Feature
