Repository kahluaband/Homepage_client_ver2.0, pull requests merged in 2024-07, with the labels that each got.

#4 Feat: performance 페이지
  app/page.tsx
  app/performance/page.tsx
  atoms/index.ts
  components/Footer.tsx
  components/Header.tsx
  components/performance/MainContainer.tsx
  components/performance/Playlists.tsx
  components/performance/YearSelector.tsx
  next.config.mjs
  package-lock.json
  package.json
  public/image/performance/chevron-down-blue.svg
  public/image/performance/chevron-down.svg
  public/image/performance/chevron-up.svg
  public/image/performance/thumbnails/1.avif
  public/image/performance/thumbnails/10.avif
  public/image/performance/thumbnails/11.avif
  public/image/performance/thumbnails/12.avif
  public/image/performance/thumbnails/13.avif
  public/image/performance/thumbnails/14.avif
  public/image/performance/thumbnails/15.avif
  public/image/performance/thumbnails/2.avif
  public/image/performance/thumbnails/3.avif
  public/image/performance/thumbnails/4.avif
  public/image/performance/thumbnails/5.avif
  public/image/performance/thumbnails/6.avif
  public/image/performance/thumbnails/7.avif
  public/image/performance/thumbnails/8.avif
  public/image/performance/thumbnails/9.avif
Labels: ✨ Feature

#6 Feat: 예매하기 + 신입생 폼 + 일반 폼 개발
  app/ticket/(reserve)/complete/page.tsx
  app/ticket/(reserve)/freshman_tickets/page.tsx
  app/ticket/(reserve)/general_tickets/page.tsx
  app/ticket/page.tsx
  app/ticket/reserve/page.tsx
  components/templates/ticket/FinalStep.tsx
  components/templates/ticket/FreshmanInfo.tsx
  components/templates/ticket/GeneralInfo.tsx
  components/templates/ticket/InfoTemplate.tsx
  components/templates/ticket/MemberSelection.tsx
  components/templates/ticket/PartySelection.tsx
  components/templates/ticket/PaymentSelection.tsx
  components/templates/ticket/TicketOption.tsx
  components/templates/ticket/TicketSelection.tsx
  components/templates/ticket/Warning.tsx
  components/ui/Bar.tsx
  components/ui/OptionBox.tsx
  components/ui/Ticket.tsx
  components/ui/input.tsx
  components/ui/selectBox.tsx
  public/image/ticket/Poster.svg
  public/image/ticket/addplus.svg
  public/image/ticket/check.svg
  public/image/ticket/share.svg
  public/image/ticket/subtract.svg
Labels: ✨ Feature

#5 Feat: about 페이지
  .gitignore
  app/about/page.tsx
  app/globals.css
  components/Header.tsx
  components/about/Banner.tsx
  components/about/Card.tsx
  components/about/OneImage.tsx
  components/about/Skeleton.tsx
  components/about/TwoImages.tsx
  public/image/about/beer.svg
  public/image/about/celebrate.svg
  public/image/about/concert1.avif
  public/image/about/concert2.avif
  public/image/about/concert3.avif
  public/image/about/ensemble1.avif
  public/image/about/ensemble2.avif
  public/image/about/ensemble3.avif
  public/image/about/guitar.svg
  public/image/about/music.svg
  public/image/about/networking1.avif
  public/image/about/networking2.avif
  public/image/about/networking3.avif
  public/image/about/travel1.avif
  public/image/about/travel2.avif
  public/image/about/travel3.avif
  tailwind.config.ts
Labels: ✨ Feature

#12 Feat: 예매하기 모든 페이지 및 모달창 UI 완성
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  app/layout.tsx
  app/ticket/(check)/cancel/page.tsx
  app/ticket/(check)/reservation/page.tsx
  app/ticket/(check)/search/page.tsx
  app/ticket/(reserve)/complete/page.tsx
  app/ticket/(reserve)/freshman_ticket/page.tsx
  app/ticket/(reserve)/general_ticket/page.tsx
  app/ticket/search/page.tsx
  components/popups/ticket/CancelModal.tsx
  components/popups/ticket/DetailsErrorModal.tsx
  components/popups/ticket/LastCheckModal.tsx
  components/popups/ticket/ReservedErrorModal.tsx
  components/templates/ticket/FinalStep.tsx
  components/templates/ticket/GeneralInfo.tsx
  components/templates/ticket/InfoTemplate.tsx
  components/templates/ticket/MustRead.tsx
  components/templates/ticket/PartySelection.tsx
  components/templates/ticket/TicketOption.tsx
  components/templates/ticket/TicketStatus.tsx
  components/ui/CancelButton.tsx
  components/ui/ModalInput.tsx
  components/ui/input.tsx
  components/ui/selectBox.tsx
  public/image/black_x.svg
  public/image/tabler_x.svg
Labels: ✨ Feature, ✒️ Fix

#19 Design: performance 반응형 및 수정 / header, footer 반응형 구현
  app/(admin)/kahlua-admin/layout.tsx
  app/(admin)/kahlua-admin/page.tsx
  app/(admin)/login/layout.tsx
  app/(admin)/login/page.tsx
  app/globals.css
  app/kahlua-admin/page.tsx
  app/layout.tsx
  app/performance/page.tsx
  components/Footer.tsx
  components/Header.tsx
  components/admin/AdminHeader.tsx
  components/admin/LoginBox.tsx
  components/performance/MainContainer.tsx
  components/performance/Playlists.tsx
  components/performance/YearSelector.tsx
  public/image/admin/bg_KAHLUA.svg
  public/image/tabler_menu-2.svg
Labels: 🔮Design, ✒️ Fix

#24 Feat: 예매 페이지 반응형
  app/ticket/(check)/cancel/page.tsx
  app/ticket/(check)/reservation/page.tsx
  app/ticket/(check)/search/page.tsx
  app/ticket/(reserve)/complete/page.tsx
  app/ticket/(reserve)/freshman_ticket/page.tsx
  app/ticket/(reserve)/general_ticket/page.tsx
  components/templates/ticket/CancelRead.tsx
  components/templates/ticket/FinalStep.tsx
  components/templates/ticket/FreshmanInfo.tsx
  components/templates/ticket/GeneralInfo.tsx
  components/templates/ticket/InfoTemplate.tsx
  components/templates/ticket/MemberSelection.tsx
  components/templates/ticket/MustRead.tsx
  components/templates/ticket/PartySelection.tsx
  components/templates/ticket/PaymentSelection.tsx
  components/templates/ticket/TicketSelection.tsx
  components/templates/ticket/TicketStatus.tsx
  components/templates/ticket/Warning.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🔮Design

#23 Feat: about page 반응형
  app/about/page.tsx
  components/about/Banner.tsx
  components/about/Card.tsx
  components/about/Concert.tsx
  components/about/Ensemble.tsx
  components/about/Networking.tsx
  components/about/OneImage.tsx
  components/about/Travel.tsx
  components/about/TwoImages.tsx
  package-lock.json
  package.json
  tailwind.config.ts
  yarn.lock
Labels: ✨ Feature, 🔮Design

#30 Fix: yarn 패키지 삭제
  package-lock.json
  yarn.lock
Labels: ✒️ Fix

#33 Feat: main page UI 구현 및 반응형 완성
  .eslintrc.json
  .vscode/settings.json
  api/auth/axios.ts
  app/globals.css
  app/layout.tsx
  app/page.tsx
  app/recruit/(application)/apply/page.tsx
  app/recruit/(application)/complete/page.tsx
  app/recruit/(application)/notice/page.tsx
  app/recruit/FAQ.tsx
  app/recruit/page.tsx
  components/main/About.tsx
  components/main/Performance.tsx
  components/main/PerformanceCard.tsx
  components/main/PerformanceList.tsx
  components/main/Recruit.tsx
  components/main/Ticket.tsx
  components/main/TicketInfo.tsx
  components/main/TicketIntro.tsx
  components/performance/SongList.ts
  components/recruit/RequirementCard.tsx
  components/recruit/ScheduleCard.tsx
  components/recruit/SessionCard.tsx
  components/templates/apply/ApplicantInfo.tsx
  components/ui/OptionBox.tsx
  components/ui/textarea.tsx
  components/ui/twoOptionbox.tsx
  package-lock.json
  package.json
  public/image/arrow_right.svg
  public/image/recruit/guitar.svg
  public/image/recruit/syn.svg
  tailwind.config.ts
  yarn.lock
Labels: ✨ Feature
