Repository kahluaband/Homepage_client_ver2.0, pull requests merged in 2025-02, with the labels that each got.

#152 Feat: 일요일 활성화 및 안내 모달 추가
  components/admin/applicant/ApplicantCard.tsx
  components/reservation/CalendarUI.tsx
  package-lock.json
  yarn.lock
Labels: ✨ Feature

#158 Feat: 공연 상세 페이지 UI 구현
  app/ticket/page.tsx
  components/data/RecommendData.ts
  components/main/TicketIntro.tsx
  components/templates/ticket/TicketStatus.tsx
  components/ticket/DesktopTicketList.tsx
  components/ticket/MobileTicketList.tsx
  components/ticket/RecommendedList.tsx
  components/ticket/WidePlaylistItem.tsx
  public/image/ticket/DefaultPoster.svg
  public/image/ticket/Poster_202503.avif
  tailwind.config.ts
Labels: ✨ Feature, 🔮Design

#157 Feat: 본인 예약 필터링 반영
  components/reservation/TimeTable.tsx
Labels: ✨ Feature, 📬 API

#159 [Feat] 공연예매현황 페이지 반응형 제작
  app/(kahlua)/admin/ticketing/page.tsx
Labels: 🔮Design

#161 Feat: 티켓 상세 페이지 구현
  app/layout.tsx
  app/page.tsx
  app/ticket/[id]/page.tsx
  app/ticket/page.tsx
  components/Header.tsx
  components/popups/ticket/LocaltionModal.tsx
  components/templates/ticket/DropdownMenu.tsx
  components/templates/ticket/TicketOption.tsx
  components/templates/ticket/TicketStatus.tsx
  components/ticket/DesktopTicketList.tsx
  components/ticket/MobileTicketList.tsx
  components/ticket/RecommendedList.tsx
  components/ticket/TicketDetail.tsx
  components/ticket/WidePlaylistItem.tsx
  components/ui/DropDownBox.tsx
  components/util/shuffleArray.ts
  next.config.mjs
Labels: ✨ Feature, 🔮Design, 📬 API

#160 Feat: Performance 페이지 제작
  components/performance/MainContainer.tsx
  components/performance/TicketList.tsx
  components/ticket/WidePlaylistItem.tsx
Labels: ✨ Feature

#162 Fix: 포스터 이미지 Rounded 위치 수정
  components/ticket/TicketDetail.tsx
  components/ticket/WidePlaylistItem.tsx
Labels: 🔮Design, ✒️ Fix

#163 Fix: 디데이 계산 방식 수정
  components/ticket/TicketDetail.tsx
Labels: 🐞 BugFix

#164 Fix: 이메일 필드 추가 및 정보 수정
  app/ticket/(reserve)/freshman_ticket/page.tsx
  app/ticket/(reserve)/general_ticket/page.tsx
  components/templates/ticket/FreshmanInfo.tsx
  components/templates/ticket/GeneralInfo.tsx
  components/templates/ticket/PartySelection.tsx
  components/templates/ticket/TicketStatus.tsx
  components/util/utils.tsx
Labels: 🐞 BugFix, ✒️ Fix

#165 Fix: 신입생일 경우 학번 취소 가능하도록 필드 설정 수정
  app/ticket/(check)/cancel/page.tsx
  app/ticket/(check)/reservation/page.tsx
Labels: ✒️ Fix

#166 Fix: 공연중->예매중 텍스트 변경
  components/performance/TicketList.tsx
  components/ticket/DesktopTicketList.tsx
  components/ticket/WidePlaylistItem.tsx
Labels: ✒️ Fix

#167 Fix: 이메일 필드 추가
  app/ticket/(reserve)/general_ticket/page.tsx
Labels: 🐞 BugFix
