Repository kahluaband/Homepage_client_ver2.0, pull requests merged in 2025-01, with the labels that each got.

#124 Feat/admin
  api/auth/axios.ts
  app/(kahlua)/admin/applicant/page.tsx
  app/(kahlua)/admin/performanceInfo/page.tsx
  app/(kahlua)/admin/recruitingInfo/page.tsx
  app/(kahlua)/admin/ticketing/page.tsx
  app/(kahlua)/callback/page.tsx
  app/(kahlua)/error/page.tsx
  app/(kahlua)/login/info/page.tsx
  app/(kahlua)/login/page.tsx
  app/PrevAdmin/admin/layout.tsx
  app/PrevAdmin/login/page.tsx
  app/layout.tsx
  atoms/authAtom.ts
  components/Header.tsx
  components/admin/AdminHeader.tsx
  components/login/ErrorModal.tsx
  components/ui/admin/ImageBox.tsx
  middleware.ts
  next.config.mjs
  package-lock.json
  package.json
Labels: 📬 API

#125 Fix: Resolving Build Error
  app/(kahlua)/announcement/posting/page.tsx
  components/announcement/posting/PageContent.tsx
  package-lock.json
  package.json
  tsconfig.json
  types/gtag.d.ts
Labels: 🌏 Deploy, ✒️ Fix

#126 feat: google login
  app/(kahlua)/login/oauth2/code/google/page.tsx
  package-lock.json
Labels: ✨ Feature

#127 Feat: 공지사항 / 깔깔깔 리스트 및 글쓰기 api 연결
  app/(kahlua)/announcement/post/[id]/page.tsx
  components/announcement/list/CommunityList.tsx
  components/announcement/list/DetailList.tsx
  components/announcement/list/List.tsx
  components/announcement/list/Toggle.tsx
  components/announcement/list/dto.ts
  components/announcement/list/dummy.ts
  components/announcement/posting/ImageUpload.tsx
  components/announcement/posting/PageContent.tsx
Labels: 🔨 Refactor, 📬 API

#128 Feat: 공지사항 상세 페이지 api 연결
  app/(kahlua)/announcement/post/[id]/page.tsx
  components/announcement/posting/PageContent.tsx
  components/notice/Comment.tsx
  components/notice/CommentInput.tsx
  components/notice/CommentList.tsx
  components/notice/LikeButton.tsx
  components/notice/Post.tsx
  components/notice/dto.ts
  components/notice/post/InfoSection.tsx
  components/notice/post/TitleSection.tsx
  components/ui/ButtonModal.tsx
  components/util/noticeUtils.ts
  next.config.mjs
  yarn.lock
Labels: 📬 API

#133 Fix: 공지사항 / 깔깔깔 리스트 댓글 개수 필터링
  components/announcement/list/DetailList.tsx
  components/announcement/list/List.tsx
  components/announcement/list/dto.ts
Labels: 🐞 BugFix

#134 Feat: mypage 기능 구현 및 Drawer 수정
  components/Header.tsx
  components/mypage/CategoryToggle.tsx
  components/mypage/List.tsx
  components/mypage/MyPostsList.tsx
  components/mypage/ReservationList.tsx
  components/mypage/UserProfile.tsx
  components/mypage/categoryDto.ts
Labels: ✨ Feature, 🔮Design, 📬 API

#135 Feat: 동아리방 예약 api 연결
  app/(kahlua)/reservation/page.tsx
  components/reservation/CalendarUI.tsx
  components/reservation/ReservationForm.tsx
  components/reservation/TimeTable.tsx
  package-lock.json
  package.json
Labels: ✨ Feature, 📬 API

#136 fix: login page 수정사항 반영
  app/(kahlua)/callback/page.tsx
  app/(kahlua)/login/info/page.tsx
  app/(kahlua)/login/oauth2/code/google/page.tsx
  app/(kahlua)/login/page.tsx
  components/main/About.tsx
  middleware.ts
  yarn.lock
Labels: ✒️ Fix

#137 Fix: announcement phone QA 반영
  components/announcement/list/AnnouncementBanner.tsx
  package-lock.json
  yarn.lock
Labels: 🐞 BugFix

#138 Fix: 배너 수정, 캘린더 관련 수정
  components/reservation/Banner.tsx
  components/reservation/CalendarUI.css
  components/reservation/CalendarUI.tsx
Labels: 🐞 BugFix

#139 hotfix: QA 반영
  components/Header.tsx
  middleware.ts
  tokenValidator.tsx
Labels: ✒️ Fix

#140 Fix: QA 반영
  middleware.ts
  tokenValidator.tsx
Labels: 🐞 BugFix

#142 Fix: 제목 길이 UI 수정
  components/announcement/list/DetailList.tsx
  components/mypage/MyPostsList.tsx
  components/notice/post/ContentSection.tsx
  components/notice/post/TitleSection.tsx
Labels: 🔮Design

#141 [Fix] 동방 예약 수정사항 반영
  app/(kahlua)/reservation/page.tsx
  components/reservation/ReservationForm.tsx
  components/reservation/TimeTable.tsx
Labels: 🐞 BugFix, ✨ Feature

#143 fix: 패딩 수정 및 넓이 오류 수정
  app/(kahlua)/announcement/post/[id]/page.tsx
  components/notice/post/TitleSection.tsx
Labels: 🔮Design

#144 Fix: mypage QA 사항 반영
  components/mypage/MyPostsList.tsx
  yarn.lock
Labels: 🐞 BugFix

#145 Fix: 댓글 컴포넌트 넓이 오류 수정
  components/notice/Comment.tsx
Labels: 🔮Design

#146 Fix: 24기 지원문구로 수정 및 공연 정보 열람 제한
  app/recruit/(application)/notice/page.tsx
  components/Header.tsx
  components/data/Information.tsx
  components/data/RecruitingInfo.ts
  components/data/SongList.ts
  components/performance/Playlists.tsx
  components/templates/apply/CLInfo.tsx
  components/templates/apply/OtherInfo.tsx
  public/image/performance/thumbnails/0.avif
Labels: 📃 Docs, ✨ Feature

#147 Fix: 마이페이지 게시글 댓글 필터링 추가
  components/mypage/MyPostsList.tsx
Labels: 📬 API, ✒️ Fix

#148 Feat: 지원자 이메일 입력란 추가
  app/recruit/(application)/apply/page.tsx
  components/templates/apply/ApplicantInfo.tsx
Labels: ✨ Feature

#149 Fix: 지원 로딩 상태 처리 및 이메일 유효성 alert 추가
  app/recruit/(application)/apply/page.tsx
  components/popups/ticket/LastCheckModal.tsx
Labels: 📬 API, ✒️ Fix

#150 Fix: 모집 일정 수정 및 티켓 컴포넌트 주석 처리
  app/page.tsx
  app/recruit/page.tsx
  components/data/RecruitingInfo.ts
Labels: 📃 Docs, 🔮Design

#151 Fix: 변수명 수정
  app/recruit/(application)/apply/page.tsx
Labels: ✒️ Fix

#153 Fix: 어드민 지원현황 반응형 작업 / 지원 현황 엑셀 변환 해결
  app/(kahlua)/admin/applicant/page.tsx
  components/admin/applicant/ApplicantCard.tsx
Labels: 🐞 BugFix, 🔮Design

#154 Feat: 어드민 페이지 공연/지원자 통계 정보 추가 및 레이아웃 수정
  app/(kahlua)/admin/page.tsx
  components/admin/adminPageButton.tsx
  components/admin/applicant/ApplicantStatistics.tsx
  components/admin/applicant/PieChart.tsx
  components/admin/ticketing/TicketStatistics.tsx
  package.json
  yarn.lock
Labels: ✨ Feature, 📬 API

#155 Fix: 헤더 내 티켓 클릭 시 접근 제한 추가
  components/Header.tsx
Labels: 🐞 BugFix

#156 Fix: 푸터 내 티켓 조회 버튼 주석 처리
  components/Footer.tsx
Labels: 🐞 BugFix
