Repository kahluaband/Homepage_client_ver2.0, pull requests merged in 2025-03, with the labels that each got.

#168 Feat: 링크 썸네일 이미지 추가
  app/layout.tsx
  public/image/Link_thumbnail.svg
Labels: 🔮Design

#169 Fix: 확장자 png로 변경
  app/layout.tsx
  public/image/Link_thumbnail.svg
  public/image/Thumbnail.png
Labels: 🐞 BugFix

#170 Feat: 공연정보생성 추가, 동방예약 버그 수정
  app/(kahlua)/admin/performanceInfo/page.tsx
  app/(kahlua)/admin/performanceInfo/performanceData.ts
  components/admin/EditModal.tsx
  components/reservation/CalendarUI.tsx
  components/templates/admin/Info.tsx
  next.config.mjs
Labels: 🐞 BugFix, 📬 API

#171 Fix: 2025년 1학기 동아리방 사용 요일 수정 (화수금)
  components/reservation/CalendarUI.tsx
Labels: ✒️ Fix

#172 Fix: 기수 계산 함수 추가
  app/(kahlua)/login/info/page.tsx
Labels: ✒️ Fix

#174 Fix: 공연상세정보 api 요청 url 수정
  components/ticket/TicketDetail.tsx
Labels: 📬 API, ✒️ Fix

#176 #175 Feat: fix head component in applying google tag
  app/layout.tsx
Labels: ✒️ Fix

#178 Fix: 어드민 공연 예매내역 상세 조회 UI 수정
  app/(kahlua)/admin/ticketing/page.tsx
  components/admin/applicant/ApplicantCard.tsx
  components/admin/ticketing/MobileTicketLists.tsx
  components/admin/ticketing/TicketInfoSection.tsx
  components/admin/ticketing/TicketLists.tsx
  public/image/admin/arrowUp.svg
Labels: 🔮Design, ✒️ Fix
