Repository kahluaband/Homepage_client_ver2.0, pull requests merged in 2025-04, with the labels that each got.

#179 [Feat] 공연 정보 수정 페이지 추가, 동방 예약 에러 해결
  app/(kahlua)/admin/page.tsx
  app/(kahlua)/admin/performance/[id]/page.tsx
  components/admin/EditModal.tsx
  components/reservation/CalendarUI.css
  components/reservation/TimeTable.tsx
  components/ticket/TicketDetail.tsx
Labels: ✨ Feature, 🔮Design, ✒️ Fix

#180 Feat: 동아리방 예약 실시간 반영
  app/(kahlua)/reservation/page.tsx
  components/reservation/TimeTable.tsx
Labels: 🐞 BugFix, ✨ Feature

#181 Feat: 어드민 타입 관리 기능 구현 및 어드민 페이지 UI 추가
  app/(kahlua)/admin/member/page.tsx
  app/(kahlua)/admin/message/page.tsx
  app/(kahlua)/admin/page.tsx
  app/globals.css
  components/admin/Header.tsx
  components/admin/adminPageButton.tsx
  components/admin/applicant/PieChart.tsx
  components/admin/member/SearchBar.tsx
  components/admin/member/StatusIcon.tsx
  components/admin/member/dto.ts
  components/admin/member/table/DropdownMenu.tsx
  components/admin/member/table/Table.tsx
  components/admin/member/table/TableHeader.tsx
  components/admin/member/table/TableRow.tsx
  components/admin/member/table/TableSection.tsx
  components/admin/message/MessageStatistics.tsx
  components/admin/ticketing/TicketStatistics.tsx
  components/main/TicketIntro.tsx
  components/ticket/WidePlaylistItem.tsx
  next.config.mjs
  public/image/admin/CompletedIcon.svg
  public/image/admin/CompletedMobileIcon.svg
  public/image/admin/SearchIcon.svg
  public/image/admin/WaitingIcon.svg
  public/image/admin/WaitingMobileIcon.svg
Labels: ✨ Feature, 🔮Design, 📬 API

#182 Design: 어드민 페이지 디자인 수정사항 반영
  components/admin/adminPageButton.tsx
  components/admin/applicant/PieChart.tsx
  components/admin/member/table/Table.tsx
  components/admin/member/table/TableRow.tsx
  components/admin/member/table/TableSection.tsx
Labels: ✨ Feature, 🔮Design
